version: '3.4'
 
x-worker-variables: &worker-variables
    WORKER_MODE: service
    BrokerServiceOptions__ServerUrl: "nats://host.docker.internal:4222" # Windows only!
    BrokerServiceOptions__Username: "testuser"
    BrokerServiceOptions__Password: "password"

services:
  # NATS Node 
  netcoresamples.broker.nats:
    image: nats:latest
    container_name: "NetCoreSamples.Broker.Nats"
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats-data:/data
    command: >
      -js
      -name nats-node
      -store_dir /data
      --user testuser 
      --pass password

  # ----- PubSub Workers -----
  # Worker 1 - Subscriber
  netcoresamples.broker.subscriber.worker:
    container_name: "NetCoreSamples.Broker.Subscriber.Worker"
    image: ${DOCKER_REGISTRY-}netcoresamplesbrokersubscriberworker
    build:
      context: .
      dockerfile: NetCoreSamples.Broker.Worker/Dockerfile
    environment:
      <<: *worker-variables
      WorkerOptions__Name: Subscriber
    depends_on: 
      - netcoresamples.broker.nats

  # Worker 2 - Publisher
  netcoresamples.broker.publisher.worker:
    container_name: "NetCoreSamples.Broker.Publisher.Worker"
    image: ${DOCKER_REGISTRY-}netcoresamplesbrokerpublisherworker
    build:
      context: .
      dockerfile: NetCoreSamples.Broker.Worker/Dockerfile
    environment:
      <<: *worker-variables
      WorkerOptions__Name: Publisher
    depends_on: 
      - netcoresamples.broker.nats

  # ----- Queue Workers -----
  # Worker 1 - Producer
  netcoresamples.broker.queueproducer.worker:
    container_name: "NetCoreSamples.Broker.QueueProducer.Worker"
    image: ${DOCKER_REGISTRY-}netcoresamplesbrokerqueueproducerworker
    build:
      context: .
      dockerfile: NetCoreSamples.Broker.Worker/Dockerfile
    environment:
      <<: *worker-variables
      WorkerOptions__Name: QueueProducer
    depends_on: 
      - netcoresamples.broker.nats

  # Worker 2 - Consumer #1
  netcoresamples.broker.queueconsumer.worker:
    container_name: "NetCoreSamples.Broker.QueueConsumer.Worker"
    image: ${DOCKER_REGISTRY-}netcoresamplesbrokerqueueconsumerworker
    build:
      context: .
      dockerfile: NetCoreSamples.Broker.Worker/Dockerfile
    environment:
      <<: *worker-variables
      WorkerOptions__Name: QueueConsumer
    depends_on: 
      - netcoresamples.broker.nats

  # Worker 3 - Consumer #2
  netcoresamples.broker.queueconsumer2.worker:
    container_name: "NetCoreSamples.Broker.QueueConsumer2.Worker"
    image: ${DOCKER_REGISTRY-}netcoresamplesbrokerqueueconsumerworker
    build:
      context: .
      dockerfile: NetCoreSamples.Broker.Worker/Dockerfile
    environment:
      <<: *worker-variables
      WorkerOptions__Name: QueueConsumer
    depends_on: 
      - netcoresamples.broker.nats

volumes:
  nats-data:
