version: '3.4'
 
x-common-variables: &common-variables
    WORKER_MODE: service
    MessageHubClientOptions__EndpointUrl: "http://host.docker.internal:8080"
    MessageHubClientOptions__DefaultHub: "tasks"

services:
  # Messaging API
  netcoresamples.messaging.signalr:
    container_name: "NetCoreSamples.Messaging.SignalR"
    image: ${DOCKER_REGISTRY-}netcoresamplesmessagingsignalr
    build:
      context: .
      dockerfile: NetCoreSamples.Messaging.SignalR/Dockerfile
    ports:
      - "8081:8081"
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_HTTP_PORTS=8080
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  # Worker 1 - Message Processor
  netcoresamples.messaging.processor.worker:
    container_name: "NetCoreSamples.Messaging.Processor.Worker"
    image: ${DOCKER_REGISTRY-}netcoresamplesmessagingprocessorworker
    build:
      context: .
      dockerfile: NetCoreSamples.Messaging.Worker/Dockerfile
    environment:
      <<: *common-variables
      WorkerOptions__Name: MessageProcessor
    depends_on: 
      - netcoresamples.messaging.signalr

  # Worker 2 - Message Publisher
  netcoresamples.messaging.publisher.worker:
    container_name: "NetCoreSamples.Messaging.Publisher.Worker"
    image: ${DOCKER_REGISTRY-}netcoresamplesmessagingpublisherworker
    build:
      context: .
      dockerfile: NetCoreSamples.Messaging.Worker/Dockerfile
    environment:
      <<: *common-variables
      WorkerOptions__Name: MessagePublisher
    depends_on: 
      - netcoresamples.messaging.signalr

