name: netcoresamples_vault
services:
  # Database - PostgreSQL 
  netcoresamples.vault.database:
    container_name: netcoresamples.vault.database
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "Passw0rd"
      POSTGRES_USERNAME: "postgres"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - netcoresamples.vault.database:/var/lib/postgresql/data
      
  # Vault
  netcoresamples.vault:
    container_name: netcoresamples.vault
    image: hashicorp/vault:latest
    restart: always
    ports:
      - "8200:8200"
    volumes:
      - netcoresamples.vault:/vault/file
    
  # API
  netcoresamples.vault.api:
    container_name: netcoresamples.vault.api
    image: ${DOCKER_REGISTRY-}netcoresamplesvaultapi
    build:
      context: .
      dockerfile: NetCoreSamples.Vault.API/Dockerfile

volumes:
  netcoresamples.vault.database:
        external: false
  netcoresamples.vault:
        external: false