services:
  netcoresamples.db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      MSSQL_SA_PASSWORD: "P@ssw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - netcoresamples.db:/var/opt/mssql
      
volumes:
    netcoresamples.db:
        name: netcoresamples.db
        external: false
  