name: netcoresamples-caching
services:
  # Web API
  netcoresamples.caching.client:
    image: ${DOCKER_REGISTRY-}netcoresamplescachingclient
    build:
      context: .
      dockerfile: NetCoreSamples.Caching.Client/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      AllowedHosts: "*"
      ConnectionStrings__DefaultConnection: "Data Source=host.docker.internal:1433;Initial Catalog=NetCoreSamples.Database;TrustServerCertificate=true;User ID=sa;Password=P@ssw0rd"
      Redis__Endpoints__0__Host: "netcoresamples.caching.redis"
      Redis__Endpoints__0__Port: "6379"
      Redis__InstanceName: "WebClient"
      Redis__Password: "redis"
      Redis__Timeout: "300"
     
  # Redis Node
  netcoresamples.caching.redis:
    container_name: netcoresamples.caching.redis
    image: redis:latest
    volumes:
      - redis_data:/data
    environment:
      REDIS_PASSWORD: "redis"
      
volumes:
  redis_data:
    name: redis_data